version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - obecker
    commit-message:
      prefix: ":arrow_up: "

  - package-ecosystem: gradle
    directory: backend
    schedule:
      interval: daily
    assignees:
      - obecker
    commit-message:
      prefix: ":arrow_up: "
    groups:
      kotlin:
        patterns:
          - jvm
          - com.google.devtools.ksp

  - package-ecosystem: npm
    directory: frontend
    schedule:
      interval: daily
    assignees:
      - obecker
    commit-message:
      prefix: ":arrow_up: "
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/js"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: terraform
    directory: infrastructure
    schedule:
      interval: daily
    assignees:
      - obecker
    commit-message:
      prefix: ":arrow_up: "

  - package-ecosystem: docker
    directory: "scripts/docker"
    schedule:
      interval: weekly
    assignees:
      - obecker
    commit-message:
      prefix: ":arrow_up: "
