# run: docker compose up --build

services:

  dynamodb:
    # instead of "image: ...", use service specific Dockerfile, which will be updated by dependabot
    # see https://github.com/dependabot/dependabot-core/issues/390#issuecomment-1062170379
    build:
      context: docker
      dockerfile: dynamodb.Dockerfile
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - '8000:8000'
    volumes:
      - "./docker_data/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  minio:
    build:
      context: docker
      dockerfile: minio.Dockerfile
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './docker_data/minio:/data'
    environment:
      - MINIO_ROOT_USER=dummyAccessKey
      - MINIO_ROOT_PASSWORD=dummyAccessSecret
