version: '3.8'

# run: docker compose up

services:

  dynamodb:
    image: amazon/dynamodb-local:2.2.1
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - '8000:8000'
    volumes:
      - "./docker_data/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  minio:
    image: quay.io/minio/minio:RELEASE.2024-02-17T01-15-57Z
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './docker_data/minio:/data'
    environment:
      - MINIO_ROOT_USER=dummyAccessKey
      - MINIO_ROOT_PASSWORD=dummyAccessSecret
