# This workflow will build the backend project with Gradle
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build backend

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 17
          distribution: corretto
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4.3.0 # https://github.com/marketplace/actions/build-with-gradle
        with:
          add-job-summary-as-pr-comment: on-failure
      - name: Execute Gradle build
        working-directory: backend
        run: ./gradlew build --warning-mode all
      - name: Create build artifacts
        uses: actions/upload-artifact@v4.6.0 # https://github.com/marketplace/actions/upload-a-build-artifact
        if: always()
        with:
          name: reports
          path: backend/build/reports
