# This workflow will build the frontend with node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3 # see https://github.com/actions/setup-node
        with:
          node-version: '21.x'
          cache: 'npm'
          cache-dependency-path: "frontend"
      - name: Clean install
        working-directory: frontend
        run: npm ci
      - name: Build
        working-directory: frontend
        run: npm run build
