# This workflow will build the frontend with node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build frontend

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0 # see https://github.com/pnpm/action-setup
        with:
          package_json_file: frontend/package.json
      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0 # see https://github.com/actions/setup-node
        with:
          node-version: '22.x'
          cache-dependency-path: "frontend"
      - name: Check dependency constraints
        working-directory: frontend
        run: pnpm install --resolution-only --no-frozen-lockfile # https://github.com/pnpm/pnpm/issues/7087
      - name: Install dependencies
        working-directory: frontend
        run: pnpm install
      - name: Lint
        working-directory: frontend
        run: pnpm run lint
      - name: Test
        working-directory: frontend
        run: pnpm run test
      - name: Build
        working-directory: frontend
        run: pnpm run build
