name: Validate infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'infrastructure/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'infrastructure/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1 # see https://github.com/hashicorp/setup-terraform
      - name: Init
        working-directory: infrastructure
        run: terraform init
      - name: Validate
        working-directory: infrastructure
        run: terraform validate -no-color
      - name: Format
        working-directory: infrastructure
        run: terraform fmt --check
