name: Check for Gradle upgrade

on:
  schedule:
    - cron: '15 4 * * 1,4' # Mon+Thu at 4:15

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate access token
        uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Upgrade Gradle
        id: upgrade-gradle
        uses: EdwarDDay/upgrade-gradle-action@v1.3.0
        with:
          working-directory: backend

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6.0.3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ":arrow_up: Upgrade gradle to ${{ steps.upgrade-gradle.outputs.gradle-version }}"
          branch: "gradle_upgrade/version_${{ steps.upgrade-gradle.outputs.gradle-version }}"
          base: main
          delete-branch: true
          title: ":arrow_up: Upgrade gradle to ${{ steps.upgrade-gradle.outputs.gradle-version }}"
          body: |
            ${{ steps.upgrade-gradle.outputs.version-information }}

            Automated changes by [upgrade-gradle-action](https://github.com/EdwarDDay/upgrade-gradle-action) and [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub actions
          labels: "dependencies,gradle"
          assignees: obecker
